name: node-app

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check-out
        uses: actions/checkout@v4
      
      - name: configure aws credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: $ {{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret_access-key: $ {{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: $ {{ secrets.AWS_REGION }}

      - name: login to amazon ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build docker images
        run:  docker build -t $ {{secrets.ECR_REPO}}:latest .

      - name: push docker image to ECR
        run: docker push $ {{secrets.ECR_REPO}}:latest .